<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>Nullable</WarningsAsErrors>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    </PropertyGroup> 

    <ItemGroup>
        <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Leda.Lang\Leda.Lang.csproj"/>
        <ProjectReference Include="..\Leda.Testing\Leda.Testing.csproj"/>
    </ItemGroup>

</Project>
